  -------------- BAIXA DE PROCESSOS EM CATORIO-------
  /**
  autor: Jader
  data: 04/10/2023
  **/

  IF(@VLRBAIXA > 0  AND @DHBAIXA IS NOT NULL)
  BEGIN
	IF(@ENV_CARTORIO = 'S')
	BEGIN
		DECLARE @NEWDATE DATETIME
		DECLARE @DTA DATETIME
		
		SET @NEWDATE = (SELECT DATEADD(DAY, DATEDIFF(DAY, -1, @DHBAIXA) -1, 1)) 
		SET @DTA = (SELECT DATEPART(weekday, @NEWDATE))
		
		--Verifica se o proximo dia é sabado, se for vai para baixa na segunda feira
		IF (@DTA = 7)
		BEGIN
			SET @NEWDATE = (SELECT DATEADD(DAY, DATEDIFF(DAY, -1, @NEWDATE) -1, 2))
			
			-- Verifica se o dia é feriado
			IF EXISTS (SELECT DTFERIADO FROM TSIFER WHERE DTFERIADO = @NEWDATE)
			BEGIN
				SET @NEWDATE = (SELECT DATEADD(DAY, DATEDIFF(DAY, -1, @NEWDATE) -1, 1))
				UPDATE TGFFIN SET DHBAIXA = @NEWDATE WHERE NUFIN = @NUFIN
				UPDATE TGFMBC SET DTLANC = @NEWDATE, PREDATA = @NEWDATE  WHERE NUMDOC = @NUMNOTA
			END
			IF NOT EXISTS (SELECT DTFERIADO FROM TSIFER WHERE DTFERIADO = @NEWDATE)
			BEGIN
				UPDATE TGFFIN SET DHBAIXA = @NEWDATE WHERE NUFIN = @NUFIN
				UPDATE TGFMBC SET DTLANC = @NEWDATE, PREDATA = @NEWDATE  WHERE NUMDOC = @NUMNOTA
			END
		END

		-- Verifica se o proximo dia é domingo, se for vai para baixa na segunda feira.
		IF (@DTA = 1)
		BEGIN
			
			SET @NEWDATE = (SELECT DATEADD(DAY, DATEDIFF(DAY, -1, @NEWDATE) -1, 1))
			
			--Verifica se o proximo dia é feriodo.
			IF EXISTS (SELECT DTFERIADO FROM TSIFER WHERE DTFERIADO = @NEWDATE)
			BEGIN
				SET @NEWDATE = (SELECT DATEADD(DAY, DATEDIFF(DAY, -1, @NEWDATE) -1, 1))
				UPDATE TGFFIN SET DHBAIXA = @NEWDATE WHERE NUFIN = @NUFIN
				UPDATE TGFMBC SET DTLANC = @NEWDATE, PREDATA = @NEWDATE  WHERE NUMDOC = @NUMNOTA
			END
			IF NOT EXISTS (SELECT DTFERIADO FROM TSIFER WHERE DTFERIADO = @NEWDATE)
			BEGIN
				UPDATE TGFFIN SET DHBAIXA = @NEWDATE WHERE NUFIN = @NUFIN
				UPDATE TGFMBC SET DTLANC = @NEWDATE, PREDATA = @NEWDATE  WHERE NUMDOC = @NUMNOTA
			END
		END

		-- verifica se o proximo é dia na semana
		IF(@DTA <> 1 OR @DTA <> 7)
		BEGIN
			--Verifica se é feriado
			IF EXISTS (SELECT DTFERIADO FROM TSIFER WHERE DTFERIADO = @NEWDATE)
			BEGIN
			
				SET @NEWDATE = (SELECT DATEADD(DAY, DATEDIFF(DAY, -1, @NEWDATE) -1, 1))
				UPDATE TGFFIN SET DHBAIXA = @NEWDATE WHERE NUFIN = @NUFIN
				UPDATE TGFMBC SET DTLANC = @NEWDATE, PREDATA = @NEWDATE  WHERE NUMDOC = @NUMNOTA
			END
			IF NOT EXISTS (SELECT DTFERIADO FROM TSIFER WHERE DTFERIADO = @NEWDATE)
			BEGIN
				UPDATE TGFFIN SET DHBAIXA = @NEWDATE WHERE NUFIN = @NUFIN
				UPDATE TGFMBC SET DTLANC = @NEWDATE, PREDATA = @NEWDATE  WHERE NUMDOC = @NUMNOTA
			END
			
		END

	END

  END